"use client"

import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"

interface Employee {
  id: string
  name: string
  role: string
  department: string
  email: string
  phone: string
  adaptabilityIndex: number
  learningUtilizationRate: number
  skillRetentionRate: number
  peerImpactScore: number
  tags: string[]
  summary: string
}

interface ExportPDFProps {
  employee: Employee
}

export function ExportPDF({ employee }: ExportPDFProps) {
  const handleExport = () => {
    // Create a simple HTML content for PDF export
    const content = `
      <html>
        <head>
          <title>${employee.name} - Talent Profile</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .header { border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
            .metric { margin: 15px 0; }
            .tags { margin: 20px 0; }
            .tag { background: #e5e7eb; padding: 4px 8px; border-radius: 4px; margin-right: 8px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${employee.name}</h1>
            <p>${employee.role} • ${employee.department}</p>
            <p>Email: ${employee.email} | Phone: ${employee.phone}</p>
          </div>
          
          <h2>Performance Metrics</h2>
          <div class="metric">
            <strong>Adaptability Index:</strong> ${employee.adaptabilityIndex}/100
          </div>
          <div class="metric">
            <strong>Learning Utilization Rate:</strong> ${employee.learningUtilizationRate}/100
          </div>
          <div class="metric">
            <strong>Skill Retention Rate:</strong> ${employee.skillRetentionRate}/100
          </div>
          <div class="metric">
            <strong>Peer Impact Score:</strong> ${employee.peerImpactScore}/100
          </div>
          
          <h2>AI-Generated Tags</h2>
          <div class="tags">
            ${employee.tags.map((tag) => `<span class="tag">${tag}</span>`).join("")}
          </div>
          
          <h2>Summary</h2>
          <p>${employee.summary}</p>
          
          <div style="margin-top: 40px; font-size: 12px; color: #666;">
            Generated by TalentCanvas on ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `

    // Create a new window and print
    const printWindow = window.open("", "_blank")
    if (printWindow) {
      printWindow.document.write(content)
      printWindow.document.close()
      printWindow.print()
    }
  }

  return (
    <Button onClick={handleExport} variant="outline">
      <Download className="w-4 h-4 mr-2" />
      Export PDF
    </Button>
  )
}
